// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie-service.proto

package com.dailyjava.grpcflix.movie;

/**
 * Protobuf type {@code MovieSearchResponse}
 */
public  final class MovieSearchResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MovieSearchResponse)
    MovieSearchResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MovieSearchResponse.newBuilder() to construct.
  private MovieSearchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MovieSearchResponse() {
    movie_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MovieSearchResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              movie_ = new java.util.ArrayList<MovieDto>();
              mutable_bitField0_ |= 0x00000001;
            }
            movie_.add(
                input.readMessage(MovieDto.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        movie_ = java.util.Collections.unmodifiableList(movie_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MovieServiceOuterClass.internal_static_MovieSearchResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MovieServiceOuterClass.internal_static_MovieSearchResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MovieSearchResponse.class, Builder.class);
  }

  public static final int MOVIE_FIELD_NUMBER = 1;
  private java.util.List<MovieDto> movie_;
  /**
   * <code>repeated .MovieDto movie = 1;</code>
   */
  public java.util.List<MovieDto> getMovieList() {
    return movie_;
  }
  /**
   * <code>repeated .MovieDto movie = 1;</code>
   */
  public java.util.List<? extends MovieDtoOrBuilder>
      getMovieOrBuilderList() {
    return movie_;
  }
  /**
   * <code>repeated .MovieDto movie = 1;</code>
   */
  public int getMovieCount() {
    return movie_.size();
  }
  /**
   * <code>repeated .MovieDto movie = 1;</code>
   */
  public MovieDto getMovie(int index) {
    return movie_.get(index);
  }
  /**
   * <code>repeated .MovieDto movie = 1;</code>
   */
  public MovieDtoOrBuilder getMovieOrBuilder(
      int index) {
    return movie_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < movie_.size(); i++) {
      output.writeMessage(1, movie_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < movie_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, movie_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MovieSearchResponse)) {
      return super.equals(obj);
    }
    MovieSearchResponse other = (MovieSearchResponse) obj;

    boolean result = true;
    result = result && getMovieList()
        .equals(other.getMovieList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMovieCount() > 0) {
      hash = (37 * hash) + MOVIE_FIELD_NUMBER;
      hash = (53 * hash) + getMovieList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MovieSearchResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MovieSearchResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MovieSearchResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MovieSearchResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MovieSearchResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MovieSearchResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MovieSearchResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MovieSearchResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MovieSearchResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MovieSearchResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MovieSearchResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MovieSearchResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MovieSearchResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MovieSearchResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MovieSearchResponse)
      MovieSearchResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MovieServiceOuterClass.internal_static_MovieSearchResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MovieServiceOuterClass.internal_static_MovieSearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MovieSearchResponse.class, Builder.class);
    }

    // Construct using com.dailyjava.grpcflix.movie.MovieSearchResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMovieFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (movieBuilder_ == null) {
        movie_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        movieBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MovieServiceOuterClass.internal_static_MovieSearchResponse_descriptor;
    }

    @Override
    public MovieSearchResponse getDefaultInstanceForType() {
      return MovieSearchResponse.getDefaultInstance();
    }

    @Override
    public MovieSearchResponse build() {
      MovieSearchResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public MovieSearchResponse buildPartial() {
      MovieSearchResponse result = new MovieSearchResponse(this);
      int from_bitField0_ = bitField0_;
      if (movieBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          movie_ = java.util.Collections.unmodifiableList(movie_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.movie_ = movie_;
      } else {
        result.movie_ = movieBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MovieSearchResponse) {
        return mergeFrom((MovieSearchResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MovieSearchResponse other) {
      if (other == MovieSearchResponse.getDefaultInstance()) return this;
      if (movieBuilder_ == null) {
        if (!other.movie_.isEmpty()) {
          if (movie_.isEmpty()) {
            movie_ = other.movie_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMovieIsMutable();
            movie_.addAll(other.movie_);
          }
          onChanged();
        }
      } else {
        if (!other.movie_.isEmpty()) {
          if (movieBuilder_.isEmpty()) {
            movieBuilder_.dispose();
            movieBuilder_ = null;
            movie_ = other.movie_;
            bitField0_ = (bitField0_ & ~0x00000001);
            movieBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMovieFieldBuilder() : null;
          } else {
            movieBuilder_.addAllMessages(other.movie_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MovieSearchResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MovieSearchResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<MovieDto> movie_ =
      java.util.Collections.emptyList();
    private void ensureMovieIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        movie_ = new java.util.ArrayList<MovieDto>(movie_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        MovieDto, MovieDto.Builder, MovieDtoOrBuilder> movieBuilder_;

    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public java.util.List<MovieDto> getMovieList() {
      if (movieBuilder_ == null) {
        return java.util.Collections.unmodifiableList(movie_);
      } else {
        return movieBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public int getMovieCount() {
      if (movieBuilder_ == null) {
        return movie_.size();
      } else {
        return movieBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public MovieDto getMovie(int index) {
      if (movieBuilder_ == null) {
        return movie_.get(index);
      } else {
        return movieBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public Builder setMovie(
        int index, MovieDto value) {
      if (movieBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMovieIsMutable();
        movie_.set(index, value);
        onChanged();
      } else {
        movieBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public Builder setMovie(
        int index, MovieDto.Builder builderForValue) {
      if (movieBuilder_ == null) {
        ensureMovieIsMutable();
        movie_.set(index, builderForValue.build());
        onChanged();
      } else {
        movieBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public Builder addMovie(MovieDto value) {
      if (movieBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMovieIsMutable();
        movie_.add(value);
        onChanged();
      } else {
        movieBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public Builder addMovie(
        int index, MovieDto value) {
      if (movieBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMovieIsMutable();
        movie_.add(index, value);
        onChanged();
      } else {
        movieBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public Builder addMovie(
        MovieDto.Builder builderForValue) {
      if (movieBuilder_ == null) {
        ensureMovieIsMutable();
        movie_.add(builderForValue.build());
        onChanged();
      } else {
        movieBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public Builder addMovie(
        int index, MovieDto.Builder builderForValue) {
      if (movieBuilder_ == null) {
        ensureMovieIsMutable();
        movie_.add(index, builderForValue.build());
        onChanged();
      } else {
        movieBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public Builder addAllMovie(
        Iterable<? extends MovieDto> values) {
      if (movieBuilder_ == null) {
        ensureMovieIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, movie_);
        onChanged();
      } else {
        movieBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public Builder clearMovie() {
      if (movieBuilder_ == null) {
        movie_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        movieBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public Builder removeMovie(int index) {
      if (movieBuilder_ == null) {
        ensureMovieIsMutable();
        movie_.remove(index);
        onChanged();
      } else {
        movieBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public MovieDto.Builder getMovieBuilder(
        int index) {
      return getMovieFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public MovieDtoOrBuilder getMovieOrBuilder(
        int index) {
      if (movieBuilder_ == null) {
        return movie_.get(index);  } else {
        return movieBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public java.util.List<? extends MovieDtoOrBuilder>
         getMovieOrBuilderList() {
      if (movieBuilder_ != null) {
        return movieBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(movie_);
      }
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public MovieDto.Builder addMovieBuilder() {
      return getMovieFieldBuilder().addBuilder(
          MovieDto.getDefaultInstance());
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public MovieDto.Builder addMovieBuilder(
        int index) {
      return getMovieFieldBuilder().addBuilder(
          index, MovieDto.getDefaultInstance());
    }
    /**
     * <code>repeated .MovieDto movie = 1;</code>
     */
    public java.util.List<MovieDto.Builder>
         getMovieBuilderList() {
      return getMovieFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        MovieDto, MovieDto.Builder, MovieDtoOrBuilder>
        getMovieFieldBuilder() {
      if (movieBuilder_ == null) {
        movieBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            MovieDto, MovieDto.Builder, MovieDtoOrBuilder>(
                movie_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        movie_ = null;
      }
      return movieBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MovieSearchResponse)
  }

  // @@protoc_insertion_point(class_scope:MovieSearchResponse)
  private static final MovieSearchResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MovieSearchResponse();
  }

  public static MovieSearchResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MovieSearchResponse>
      PARSER = new com.google.protobuf.AbstractParser<MovieSearchResponse>() {
    @Override
    public MovieSearchResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MovieSearchResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MovieSearchResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MovieSearchResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public MovieSearchResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

