// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie-service.proto

package com.dailyjava.grpcflix.movie;

public interface MovieSearchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MovieSearchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .MovieDto movie = 1;</code>
   */
  java.util.List<MovieDto>
      getMovieList();
  /**
   * <code>repeated .MovieDto movie = 1;</code>
   */
  MovieDto getMovie(int index);
  /**
   * <code>repeated .MovieDto movie = 1;</code>
   */
  int getMovieCount();
  /**
   * <code>repeated .MovieDto movie = 1;</code>
   */
  java.util.List<? extends MovieDtoOrBuilder>
      getMovieOrBuilderList();
  /**
   * <code>repeated .MovieDto movie = 1;</code>
   */
  MovieDtoOrBuilder getMovieOrBuilder(
      int index);
}
