// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie-service.proto

package com.dailyjava.grpcflix.movie;

public interface MovieSearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MovieSearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.common.Genre genre = 1;</code>
   */
  int getGenreValue();
  /**
   * <code>.common.Genre genre = 1;</code>
   */
  com.dailyjava.grpcflix.common.Genre getGenre();
}
